web:
  image: wordpress:4.8-php7.0-apache
  restart: always
  container_name: syncdb
  ports:
    - "8080:80"
  environment:
    WORDPRESS_DB_PASSWORD: wordpress
  links:
    - mysql:mysql
  volumes:
    - ./www:/var/www/html

mysql:
  image: mysql:5.7
  restart: always
  ports:
    - "3306:3306"
  container_name: syncdbdb
  environment:
    MYSQL_ROOT_PASSWORD: wordpress